### ISSUE TITLE
Advanced settings tab disappears

### ISSUE THREAD

**Issue by Usurper1** [matzman666/OpenVR-AdvancedSettings#80]
Hey guys. So, While in VR, once I open up the Advanced Settings circle/button, and try to click on a tab within it, it instantly disappears. I cant do anything. It reappears once rebooted, but its still just disappears when I try to do anything within it.

**Comment by unkellsam** [comment]
+1 I get the same thing. I reinstalled advanced settings and it  seems to happen less frequently.

**Comment by CrispySteak** [comment]
+1 I also have this issue atm. The rest of the UI gets glitchy too and i can't select anything, requiring me to take of the hmd and go to my computer to exit steamvr.

**Comment by Martin-Oehler** [comment]
I had the same problem. I somehow fixed it by installing the two previous versions and then installing the latest version, all on top. No idea, but it works now

**Comment by matzman666** [comment]
The SteamVR Home Beta introduced some changes that caused older versions to crash. This has been fixed in versions 2.4/2.4.1.

**Comment by n4ru** [comment]
This is still occuring. I have uninstalled, delete the OVRAS folder in Program Files, reinstalled, and relaunched, but it still crashes for me, even after reinstalling SteamVR.

**Comment by Martin-Oehler** [comment]
You have an old installation somewhere. You can verify this by taking a look at the version number on the lower right of the overlay.
While the overlay is running, open the taskmanager, find the process, right click it and select "go to location" or something like that. Now delete that folder and reinstall.
